### ISSUE TITLE
Explore using Twisted in Opennamed

### ISSUE THREAD

**Issue by muneeb-ali** [openname/blockstore#33]
Thanks @bmuller for the suggestion. This can get rid of the zerorpc requirement as well (twisted is already a requirement). zerorpc also requires an additional installation step on Ubuntu/Debian. This can lead to less code as well. One downside I can think of is that event-driven code is slightly harder to follow.

**Comment by kef** [comment]
Probably time to close this.

**Comment by muneeb-ali** [comment]
Yes, resolved in 498a782680f480b5ed96483f852fcb210346dbbd
